name: hw-xml
version: '0.1.0.3'
synopsis: Conduits for tokenizing streams.
description: Conduits for tokenizing streams. Please see README.md
category: Data, XML, Succinct Data Structures, Data Structures
author:
- John Ky
- Alexey Raga
maintainer: alexey.raga@gmail.com
copyright:
- 2016 John Ky
- Alexey Raga
license: BSD3
github: haskell-works/hw-xml
homepage: http://github.com/haskell-works/hw-xml#readme
extra-source-files:
- README.md

dependencies:
- base            >= 4         && < 5
- bytestring
- vector

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -O2
  - -msse4.2
  exposed-modules:
  - HaskellWorks.Data.Xml
  - HaskellWorks.Data.Xml.Blank
  - HaskellWorks.Data.Xml.CharLike
  - HaskellWorks.Data.Xml.Conduit
  - HaskellWorks.Data.Xml.Conduit.Blank
  - HaskellWorks.Data.Xml.Conduit.Words
  - HaskellWorks.Data.Xml.Decode
  - HaskellWorks.Data.Xml.DecodeError
  - HaskellWorks.Data.Xml.DecodeResult
  - HaskellWorks.Data.Xml.Grammar
  - HaskellWorks.Data.Xml.Index
  - HaskellWorks.Data.Xml.Lens
  - HaskellWorks.Data.Xml.Succinct
  - HaskellWorks.Data.Xml.Succinct.Cursor
  - HaskellWorks.Data.Xml.Succinct.Cursor.BalancedParens
  - HaskellWorks.Data.Xml.Succinct.Cursor.BlankedXml
  - HaskellWorks.Data.Xml.Succinct.Cursor.InterestBits
  - HaskellWorks.Data.Xml.Succinct.Cursor.Internal
  - HaskellWorks.Data.Xml.Succinct.Cursor.Token
  - HaskellWorks.Data.Xml.Succinct.Index
  - HaskellWorks.Data.Xml.RawDecode
  - HaskellWorks.Data.Xml.RawValue
  - HaskellWorks.Data.Xml.Token.Tokenize
  - HaskellWorks.Data.Xml.Token.Types
  - HaskellWorks.Data.Xml.Token
  - HaskellWorks.Data.Xml.Type
  - HaskellWorks.Data.Xml.Value
  dependencies:
  - array
  - ansi-wl-pprint
  - attoparsec
  - cereal
  - conduit
  - containers
  - deepseq
  - ghc-prim
  - hw-balancedparens     >= 0.1.0.0
  - hw-bits               >= 0.4.0.0
  - hw-conduit            >= 0.2.0.2
  - hw-parser
  - hw-prim               >= 0.4.0.0
  - hw-rankselect         >= 0.7.0.0
  - hw-rankselect-base    >= 0.2.0.0
  - lens
  - mtl
  - resourcet
  - transformers
  - word8

executables:
  hw-xml-example:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -Wall
    - -msse4.2
    dependencies:
    - hw-balancedparens   >= 0.2.0.1
    - hw-bits             >= 0.7.0.2
    - hw-prim             >= 0.5.0.0
    - hw-rankselect       >= 0.10.0.3
    - hw-xml

tests:
  hw-xml-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - attoparsec
    - conduit
    - hspec
    - hw-balancedparens   >= 0.1.0.0
    - hw-bits             >= 0.4.0.0
    - hw-conduit          >= 0.2.0.2
    - hw-xml
    - hw-prim             >= 0.4.0.0
    - hw-rankselect       >= 0.7.0.0
    - hw-rankselect-base  >= 0.2.0.0
    - QuickCheck
    verbatim:
      build-tool-depends: hspec-discover:hspec-discover

benchmarks:
  bench:
    main: Main.hs
    source-dirs: bench
    ghc-options:
    - -O2
    - -Wall
    - -msse4.2
    dependencies:
    - conduit
    - criterion
    - hw-balancedparens   >= 0.1.0.0
    - hw-bits             >= 0.4.0.0
    - hw-conduit          >= 0.2.0.2
    - hw-xml
    - hw-prim             >= 0.4.0.0
    - mmap
    - resourcet

data-files:
- data/catalog.xml

when:
- condition: (flag(bmi2)) && (impl(ghc >=8.4.1))
  ghc-options:
  - -mbmi2
  - -msse4.2
  cpp-options:
  - -DBMI2_ENABLED

flags:
  bmi2:
    description: Enable bmi2 instruction set
    manual: false
    default: false
